version: '3'

services:
  application:
    # Reference built image name in CI to prevent double building with the
    # `build` config defined in `docker-compose.yml`
    image: crystal-ball/react-application-prototype

  cypress:
    # The image field will be used to name the built image, overriding to
    # include /percy for easier identification
    image: cypress/included/percy:5.1.0
    build:
      context: .
      dockerfile: ./cypress/Dockerfile
    environment:
      # Pass through env variables and tokens from ci-cd workflow for
      # Cypress+Percy to determine test run git info
      - COMMIT_INFO_BRANCH=${COMMIT_INFO_BRANCH}
      - COMMIT_INFO_MESSAGE=${COMMIT_INFO_MESSAGE}
      - COMMIT_INFO_SHA=${COMMIT_INFO_SHA}
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - PERCY_BRANCH=${PERCY_BRANCH}
      - PERCY_TOKEN=${PERCY_TOKEN}
