version: '3'

services:
  cypress:
    # The image field will be used to name the built image, overriding to
    # include /percy for easier identification
    image: cypress/included/percy:3.5
    build:
      context: .
      dockerfile: ./cypress/Dockerfile
    environment:
      # Provides required env variable to upload test runs to project dashboard
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - PERCY_TOKEN=${PERCY_TOKEN}
