version: '3'

services:
  test:
    image: crystal-ball/react-application-prototype
    ports:
      - '5000:5000'

  cypress:
    image: cypress/included:3.5.0
    # See https://github.com/cypress-io/cypress/issues/350
    ipc: host
    environment:
      - CYPRESS_baseUrl=http://test:5000
    depends_on:
      - test
    # Share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      # Mount git directory so Cypress can determine branch and commit info
      - ./.git:/e2e/.git
      # Only copy Cypress configs, the docs example of mounting the entire repo
      # like `./:/e2e` fails Cypress because then the `babel.config.js` is picked
      # up and Cypress tries to use it to transpile tests which is bad
      - ./cypress.json:/e2e/cypress.json
      - ./cypress:/e2e/cypress
