version: '3'

services:
  cypress:
    # The image field will be used to name the built image, overriding to
    # include /percy for easier identification
    image: cypress/included/percy:3.5
    build:
      context: .
      dockerfile: ./cypress/Dockerfile
    environment:
      # Provides required env variable to upload test runs to project dashboard
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY}
      - PERCY_TOKEN=${PERCY_TOKEN}
      # Cypress git env vars
      - COMMIT_INFO_BRANCH=${COMMIT_INFO_BRANCH}
      - COMMIT_INFO_MESSAGE=${COMMIT_INFO_MESSAGE}
      - COMMIT_INFO_SHA=${COMMIT_INFO_SHA}
      # - COMMIT_INFO_EMAIL=${COMMIT_INFO_EMAIL}
      # - COMMIT_INFO_AUTHOR=${COMMIT_INFO_AUTHOR}
      # - COMMIT_INFO_REMOTE=${COMMIT_INFO_REMOTE}
    volumes:
      # Mount git directory so Cypress can determine branch and commit info
      - ./.git:/e2e/.git
