version: '3'

services:
  application:
    build:
      context: .
    ports:
      - '5000:5000'

  cypress:
    image: cypress/included:4.8.0
    # See https://github.com/cypress-io/cypress/issues/350
    ipc: host
    environment:
      - CYPRESS_baseUrl=http://application:5000
      ## This enables colors in the output
      - TERM=xterm
    depends_on:
      - application
    working_dir: /e2e
    volumes:
      # Only copy Cypress configs, the docs example of mounting the entire repo
      # like `./:/e2e` fails Cypress because then the `babel.config.js` is picked
      # up and Cypress tries to use it to transpile tests which is bad
      - ./cypress.json:/e2e/cypress.json
      - ./cypress:/e2e/cypress
