name: CI/CD

# Run action on all PRS and on change to master branch in order to test PRs for
# continuous integration
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Test
        run: |
          export COMMIT_INFO_MESSAGE=$(git show $COMMIT_INFO_SHA -s --pretty=%B)
          echo "COMMIT_INFO_SHA: $COMMIT_INFO_SHA"
          echo "COMMIT_INFO_MESSAGE: $COMMIT_INFO_MESSAGE"
          echo "COMMIT_INFO_BRANCH: $COMMIT_INFO_BRANCH"
        env:
          COMMIT_INFO_BRANCH: ${{ github.head_ref }}
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
